#
# validate this script with :
# https://gitlab.maisondelasimulation.fr/pkestene/dyablo/-/ci/lint
#
image: "arnodurocher/dyablo-ci:cuda-11.0"

stages:
  - build
  - run
  - render
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive

# Global before and after script to log machine info
before_script:
  - date
  - lscpu

after_script:
  - date

# Build Dyablo
.build_template: &build_definition
  stage: build
  artifacts:
    paths:
      - build
    expire_in: 1 week

build::openmp:
  <<: *build_definition
  tags:
    - docker
  script:
    - ci/build-openmp.sh

.build_cuda_template: &build_cuda_definition
  <<: *build_definition
  before_script:
    - date
    - nvcc --version
  tags:
    - docker-cuda
  script:
    - ci/build-cuda.sh

build::cuda:
  <<: *build_cuda_definition

build::cuda-10.2:
  <<: *build_cuda_definition
  image: "arnodurocher/dyablo-ci:cuda-10.2"
  when: manual

build::cuda-9.2:
  <<: *build_cuda_definition
  image: "arnodurocher/dyablo-ci:cuda-9.2"
  when: manual

# Run unit tests
.test_template: &test_definition
  stage: test
  script: ci/run_unit_tests.sh

.openmp_template: &openmp_definition
  needs: 
    - build::openmp
  tags:
    - docker

.cuda_template: &cuda_definition
  before_script:
    - date
    - lscpu
    - nvidia-smi
  needs: 
    - build::cuda
  tags:
    - docker-cuda

test::openmp:
  <<: *test_definition
  <<: *openmp_definition

test::cuda:
  <<: *test_definition
  <<: *cuda_definition

# Run examples (optional)
.run_template: &run_definition
  stage: run
  image: "arnodurocher/dyablo-ci:cuda-11.0-visu"
  when: manual
  artifacts:
    paths:
      - render.png
    expire_in: 1 week

run::blast_3D_block::openmp:
  <<: *run_definition
  <<: *openmp_definition
  script: 
    - ci/run_testcase.sh test_blast_3D_block.ini
    - ci/render.sh visu_blast_3D_block.pvsm

run::blast_3D_block::cuda:
  <<: *run_definition
  <<: *cuda_definition
  script: 
    - ci/run_testcase.sh test_blast_3D_block.ini
    - ci/render.sh visu_blast_3D_block.pvsm

# Read ci/Readme.md for instructions on how to add new testcases





