#
# validate this script with :
# https://gitlab.maisondelasimulation.fr/pkestene/dyablo/-/ci/lint
#

stages:
  - build_openmp
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build_openmp:
  stage: build_openmp
  tags:
    - kokkos-openmp
  before_script:
    - date
    - lscpu
  script:
    - mkdir build_openmp
    - cd build_openmp
    - cmake ..
    - make
  after_script:
    - date


# run some interesting tests here
test:
  stage: test
  script:
    - date
