#
# validate this script with :
# https://gitlab.maisondelasimulation.fr/pkestene/dyablo/-/ci/lint
#
image: "arnodurocher/dyablo-ci:cuda-11.0"

stages:
  - build
  - run_all
  - run
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive

# Global before and after script to log machine info
before_script:
  - date
  - lscpu

after_script:
  - date

# Build Dyablo
.build_template: &build_definition
  stage: build
  artifacts:
    paths:
      - build
    expire_in: 1 week

build::openmp:
  <<: *build_definition
  tags:
    - docker
  script:
    - ci/build-openmp.sh

.build_cuda_template: &build_cuda_definition
  <<: *build_definition
  before_script:
    - date
    - nvcc --version
  tags:
    - docker-cuda
  script:
    - ci/build-cuda.sh

build::cuda:
  <<: *build_cuda_definition

build::cuda-10.2:
  <<: *build_cuda_definition
  image: "arnodurocher/dyablo-ci:cuda-10.2"
  when: manual

build::cuda-9.2:
  <<: *build_cuda_definition
  image: "arnodurocher/dyablo-ci:cuda-9.2"
  when: manual

# Run unit tests
.test_template: &test_definition
  stage: test
  script: ci/run_unit_tests.sh

.openmp_template: &openmp_definition
  needs: 
    - build::openmp
  tags:
    - docker

.cuda_template: &cuda_definition
  before_script:
    - date
    - lscpu
    - nvidia-smi
  needs: 
    - build::cuda
  tags:
    - docker-cuda

test::openmp:
  <<: *test_definition
  <<: *openmp_definition

test::cuda:
  <<: *test_definition
  <<: *cuda_definition

# Run examples (optional)
# ===============================
.run_template: &run_definition
  stage: run
  image: "arnodurocher/dyablo-ci:cuda-11.0-visu"
  when: manual
  artifacts:
    paths:
      - "*.png"
    expire_in: 1 week

# Run multiple testcases
# -------------------------
run_all::openmp_4mpi:
  <<: *run_definition
  <<: *openmp_definition
  stage: run_all
  script: 
    - ci/run_and_render_all.sh

run_all::cuda_4mpi:
  <<: *run_definition
  <<: *cuda_definition
  stage: run_all
  script: 
    - ci/run_and_render_all.sh

# Run separate testcases
# -------------------------
# Blast 3D block based testcase
run::blast_3D_block::openmp:
  <<: *run_definition
  <<: *openmp_definition
  script: 
    - ci/run_testcase.sh test_blast_3D_block.ini
    - ci/render.sh visu_blast_3D_block.pvsm

run::blast_3D_block::openmp_4mpi:
  <<: *run_definition
  <<: *openmp_definition
  script: 
    - ci/run_testcase_mpi.sh test_blast_3D_block.ini 4
    - ci/render.sh visu_blast_3D_block.pvsm

run::blast_3D_block::cuda:
  <<: *run_definition
  <<: *cuda_definition
  script: 
    - ci/run_testcase.sh test_blast_3D_block.ini
    - ci/render.sh visu_blast_3D_block.pvsm

run::blast_3D_block::cuda_4mpi:
  <<: *run_definition
  <<: *cuda_definition
  script: 
    - ci/run_testcase_mpi.sh test_blast_3D_block.ini 4
    - ci/render.sh visu_blast_3D_block.pvsm

# Blast 3D cell based testcase
run::blast_3D_cell::openmp:
  <<: *run_definition
  <<: *openmp_definition
  script: 
    - ci/run_testcase.sh test_blast_3D.ini
    - ci/render.sh visu_blast_3D_cell.pvsm

run::blast_3D_cell::openmp_4mpi:
  <<: *run_definition
  <<: *openmp_definition
  script: 
    - ci/run_testcase_mpi.sh test_blast_3D.ini 4
    - ci/render.sh visu_blast_3D_cell.pvsm

# Blast 2D block based testcase
run::blast_2D_block::openmp:
  <<: *run_definition
  <<: *openmp_definition
  script: 
    - ci/run_testcase.sh test_blast_2D_block.ini
    - ci/render.sh visu_blast_2D_block.pvsm

run::blast_2D_block::openmp_4mpi:
  <<: *run_definition
  <<: *openmp_definition
  script: 
    - ci/run_testcase_mpi.sh test_blast_2D_block.ini 4
    - ci/render.sh visu_blast_2D_block.pvsm

run::blast_2D_block::cuda:
  <<: *run_definition
  <<: *cuda_definition
  script: 
    - ci/run_testcase.sh test_blast_2D_block.ini
    - ci/render.sh visu_blast_2D_block.pvsm

run::blast_2D_block::cuda_4mpi:
  <<: *run_definition
  <<: *cuda_definition
  script: 
    - ci/run_testcase_mpi.sh test_blast_2D_block.ini 4
    - ci/render.sh visu_blast_2D_block.pvsm

# Blast 2D cell based testcase
run::blast_2D_cell::openmp:
  <<: *run_definition
  <<: *openmp_definition
  script: 
    - ci/run_testcase.sh test_blast_2D.ini
    - ci/render.sh visu_blast_2D_cell.pvsm

run::blast_2D_cell::openmp_4mpi:
  <<: *run_definition
  <<: *openmp_definition
  script: 
    - ci/run_testcase_mpi.sh test_blast_2D.ini 4
    - ci/render.sh visu_blast_2D_cell.pvsm


# Read ci/Readme.md for instructions on how to add new testcases





